### ISSUE TITLE
Unable to connect to spotilocal.com

### ISSUE THREAD

**Issue by NotZombieFood** [erinxocon/spotify-local#6]
Hi, 
I really like the idea behind this. I'm trying to fix this issue but im kinda lost. 

requests.exceptions.ConnectionError: HTTPConnectionPool(host='wykgcyejmu.spotilocal.com', port=4381): Max retries exceeded with url: /simplecsrf/token.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021474A58BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by Ayyorta** [comment]
i have the same issue;
"C:\Users\Ayyorta\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ylwywdlkzt.spotilocal.com', port=4381): Max retries exceeded with url: /simplecsrf/token.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CBD95EBB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

**Comment by NotZombieFood** [comment]
So it seems the Spotify local server was deprecated, @Ayyorta you may take a look at the Web API it can be  used with authentication using the following Python module [Spotify web token](https://github.com/enriquegh/spotify-webplayer-token).

**Comment by R3tr0BoiDX** [comment]
Same problem running it on Linux Mint, but as it seems, its a Spotify problem. Any fix since now?

`MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='kmzgonoofo.spotilocal.com', port=4381): Max retries exceeded with url: /simplecsrf/token.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4908bbb470>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by Ayyorta** [comment]
> Same problem running it on Linux Mint, but as it seems, its a Spotify problem. Any fix since now?
> 
> `MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='kmzgonoofo.spotilocal.com', port=4381): Max retries exceeded with url: /simplecsrf/token.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4908bbb470>: Failed to establish a new connection: [Errno 111] Connection refused',))`

The same issue still. it shouldn't have anything to do with the version, it seems to be on Spotify's end.

**Comment by erinxocon** [comment]
Spotify changes the api all the time and I haven't been super active in maintaining this!  I'll see if I can look at it this weekend!

**Comment by R3tr0BoiDX** [comment]
Any progress so far?

**Comment by erinxocon** [comment]
@NotZombieFood @Ayyorta @R3tr0BoiDX 

Apoologies everyone but it seems as if spotify has gotten rid of the local api.  The web api should be able to do everything I was doing here so I would go to spotipy or another python Spotify solution! Thanks!
